#!/bin/bash

service::config_set() {
  config::check_or_set $1 $2 $SERVICE_CONFIG "${@:3}"
}

check() {
  if [ "$DEBUG" = "true" ]; then
    log::info "[DEBUG][service]: $SERVICE_CONFIG"
    cat $SERVICE_CONFIG
  fi

  service::config_set SERVICE_ALIOSS_CDN_PORT text "Port" 8080

  service::config_set SERVICE_ALIOSS_CDN_OSS_ACCESS_KEY_ID text "OSS Access Key ID"
  service::config_set SERVICE_ALIOSS_CDN_OSS_ACCESS_KEY_SECRET text "OSS Access Key Secret"
  service::config_set SERVICE_ALIOSS_CDN_OSS_BUCKET text "OSS Bucket"
  service::config_set SERVICE_ALIOSS_CDN_OSS_ENDPOINT text "OSS Endpoint" "oss-cn-shanghai.aliyuncs.com"
  # service::config_set SERVICE_ALIOSS_CDN_OSS_DIRECTORY text "OSS Directory"
}

check $@
